import {createGame,beginFlight,aimAt,flap,step,revive,snapshot,stageAt} from './alpha3-game.mjs?v=storm-campaign-public-20261001-v1';
import {createStroke,beginStroke,updateStroke,endStroke} from './alpha3-input.mjs?v=storm-campaign-public-20261001-v1';
import {createFeedback} from './alpha3-feedback.mjs?v=storm-campaign-public-20261001-v1';
import {createEffects,noteFlap,notePickup,noteCatch,tickEffects} from './alpha4-effects.mjs?v=storm-campaign-public-20261001-v1';
import {createRenderer} from './chapters-renderer.mjs?v=storm-campaign-public-20261001-v1';
import {CHAPTERS,LEVELS,levelById} from './chapters-content.mjs?v=storm-campaign-public-20261001-v1';
import {SAVE_KEY as LAB_SAVE_KEY,RECORD_KEY as LAB_RECORD_KEY,PREF_KEY as LAB_PREF_KEY,createRun,tickRun,collectPatent,crashRun,retryRun,finishRun,snapshotSave,restoreSave,createRecords,restoreRecords,updateRecords,noteCollection} from './chapters-state.mjs?v=storm-campaign-public-20261001-v1';
import {CAMPAIGN_SAVE_KEY,CAMPAIGN_RECORD_KEY,CAMPAIGN_PREF_KEY,createCampaign,restoreCampaign,unlockedLevels,nextFlight,attachFlight,fileFlight} from './campaign-state.mjs?v=storm-campaign-public-20261001-v1';
import {overview} from './campaign-map.mjs?v=storm-campaign-public-20261001-v1';
import {renderOverview} from './campaign-overview-view.mjs?v=storm-campaign-public-20261001-v1';
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const shell=document.querySelector('.machine'),canvas=$('world'),controls=document.querySelector('.controls');
const campaignMode=shell.dataset.mode==='campaign',SAVE_KEY=campaignMode?CAMPAIGN_SAVE_KEY:LAB_SAVE_KEY,RECORD_KEY=campaignMode?CAMPAIGN_RECORD_KEY:LAB_RECORD_KEY,PREF_KEY=campaignMode?CAMPAIGN_PREF_KEY:LAB_PREF_KEY;
const aimTrack=$('aim-track'),flapTrack=$('flap-track'),aimKnob=$('aim-knob'),flapKnob=$('flap-knob');
const pauseSheet=$('pause-sheet'),victory=$('victory'),workbench=$('workbench');
if(campaignMode)shell.append(pauseSheet);
let menuReturn=null,selectedFlightId=null;
const feedback=createFeedback(),reduced=matchMedia('(prefers-reduced-motion: reduce)');
let storageFailed=false;
const read=key=>{try{return localStorage.getItem(key);}catch{storageFailed=true;return null;}};
const parse=raw=>{if(raw===null)return undefined;try{return JSON.parse(raw);}catch{return null;}};
const campaignRestore=campaignMode?restoreCampaign(parse(read(SAVE_KEY))):{status:'new',campaign:createCampaign()};
let campaign=campaignRestore.campaign;
const restored=restoreSave(campaignMode?(campaign.flight??undefined):parse(read(SAVE_KEY))),recordState=restoreRecords(parse(read(RECORD_KEY)));
let saveInvalid=restored.status==='invalid'||campaignRestore.status==='invalid',recordsInvalid=recordState.status==='invalid',prefsInvalid=false;
let records=recordState.records,level=levelById(restored.levelId),run=restored.run;
let game=createGame(restored.status==='restored'?{v:1,worldVersion:level.world.worldVersion,checkpoint:restored.checkpoint}:undefined,level.world);beginFlight(game);
let restoredFinish=restored.status==='restored'&&run.finished;
if(restoredFinish)Object.assign(game,{mode:'won',x:level.world.goal.x,y:level.world.goal.y,maxY:level.world.goal.y});
let renderer=createRenderer(canvas,level),chapterId=level.chapterId,hasFlight=restored.status==='restored';
let paused=false,last=0,time=0,impactRemaining=0,impactHeld=false,finishStarted=false,endingElapsed=0,wonShown=false;
let aim=.5,wing=0,aimPointer=null,flapPointer=null,aimKeys=new Set(),keyboardWing=false,stroke=createStroke();
let effects=createEffects();const particles=[],trail=[];
const prefs=parse(read(PREF_KEY));
if(prefs!==undefined){if(prefs&&Object.keys(prefs).length===3&&prefs.v===1&&typeof prefs.sound==='boolean'&&typeof prefs.haptics==='boolean'){$('sound-toggle').checked=prefs.sound;$('haptic-toggle').checked=prefs.haptics;}else prefsInvalid=true;}
feedback.configure({sound:$('sound-toggle').checked,haptics:$('haptic-toggle').checked});
const formatTime=ms=>`${(ms/1000).toFixed(1)}s`;
function warning(){const invalid=saveInvalid||recordsInvalid||prefsInvalid;const text=invalid?`Unreadable ${campaignMode?'campaign':'lab'} data is kept unchanged. You can play in this tab or explicitly reset it.`:storageFailed?'Storage is unavailable. This tab can play, but progress may not survive closing it.':'';$('storage-warning').textContent=text;$('storage-warning').hidden=!text;$('storage-reset').hidden=!invalid;const p=$('save-warning');p.textContent=text;p.hidden=!text;}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{storageFailed=true;warning();return false;}}
function save(){if(!hasFlight||saveInvalid)return;const flight=snapshotSave(level.id,game,run);if(campaignMode){campaign=attachFlight(campaign,flight);write(SAVE_KEY,campaign);}else write(SAVE_KEY,flight);}
function saveRecords(){if(!recordsInvalid)write(RECORD_KEY,records);}
function cue(kind,intensity=1){window.dispatchEvent(new CustomEvent('storm:cue',{detail:{kind,intensity}}));feedback.cue(kind,intensity);if(reduced.matches)return;const count=kind==='crash'?12:kind==='win'?20:0;for(let i=0;i<count&&particles.length<60;i++){const a=i*2.399;particles.push({x:game.x,y:game.y,vx:Math.cos(a)*45,vy:Math.sin(a)*45,life:.25+(i%3)*.1,color:kind==='crash'?'#ff9a7d':'#f0d5a2'});}}
function canFly(){return workbench.hidden&&!paused&&['ready','playing'].includes(game.mode);}
function setAim(f){aim=clamp(f,0,1);aimAt(game,aim);const r=aimKnob.offsetWidth/2;aimKnob.style.left=`${r+aim*Math.max(0,aimTrack.clientWidth-2*r)}px`;aimTrack.setAttribute('aria-valuenow',String(Math.round(aim*180)));aimTrack.setAttribute('aria-valuetext',aim<.35?'Left':aim>.65?'Right':'Up');}
function setWing(f){wing=clamp(f,0,1);game.wing=wing;flapKnob.style.top=`${25+wing*Math.max(0,flapTrack.clientHeight-50)}px`;flapTrack.setAttribute('aria-valuenow',String(Math.round(wing*100)));}
function kick(speed){if(!canFly())return 0;const force=flap(game,speed);if(force){noteFlap(effects,game,level.world);cue('flap',force/270);}return force;}
function releasePointer(track,id){if(id===null)return;try{if(track.hasPointerCapture(id))track.releasePointerCapture(id);}catch{}track.classList.remove('active');}
function cancelControls(){releasePointer(aimTrack,aimPointer);releasePointer(flapTrack,flapPointer);aimPointer=flapPointer=null;aimKeys.clear();keyboardWing=false;endStroke(stroke);setWing(0);}
function updateAudioStatus(){const s=feedback.state();$('audio-status').textContent=!s.sound?'Sound off':s.unlocked?'Sound ready':'Sound wakes on your first gesture';}
function unlock(){feedback.unlock().then(updateAudioStatus);}
aimTrack.addEventListener('pointerdown',e=>{if(!canFly()||aimPointer!==null)return;e.preventDefault();unlock();aimPointer=e.pointerId;aimTrack.setPointerCapture(e.pointerId);aimTrack.classList.add('active');moveAim(e);});
function moveAim(e){const r=aimTrack.getBoundingClientRect(),radius=aimKnob.offsetWidth/2;setAim((e.clientX-r.left-radius)/Math.max(1,r.width-2*radius));}
aimTrack.addEventListener('pointermove',e=>{if(e.pointerId===aimPointer&&canFly()){e.preventDefault();moveAim(e);}});
for(const type of ['pointerup','pointercancel','lostpointercapture'])aimTrack.addEventListener(type,e=>{if(e.pointerId!==aimPointer)return;aimPointer=null;aimTrack.classList.remove('active');});
const flapPosition=e=>{const r=flapTrack.getBoundingClientRect();return clamp((e.clientY-r.top-25)/Math.max(1,r.height-50),0,1);};
flapTrack.addEventListener('pointerdown',e=>{if(!canFly()||flapPointer!==null)return;e.preventDefault();unlock();flapPointer=e.pointerId;flapTrack.setPointerCapture(e.pointerId);flapTrack.classList.add('active');const p=flapPosition(e);beginStroke(stroke,p,e.timeStamp);setWing(p);});
flapTrack.addEventListener('pointermove',e=>{if(e.pointerId!==flapPointer||!canFly())return;e.preventDefault();const p=flapPosition(e),speed=updateStroke(stroke,p,e.timeStamp,Math.max(0,flapTrack.clientHeight-50));setWing(p);if(speed>0)kick(speed);});
for(const type of ['pointerup','pointercancel','lostpointercapture'])flapTrack.addEventListener(type,e=>{if(e.pointerId!==flapPointer)return;flapPointer=null;flapTrack.classList.remove('active');endStroke(stroke);});
function syncSheets(){const active=!pauseSheet.hidden||!victory.hidden;shell.classList.toggle('has-sheet',active);controls.inert=active||!canFly();$('map-button').inert=campaignMode?!pauseSheet.hidden:active||!workbench.hidden;$('pause-button').inert=campaignMode?false:active||!workbench.hidden;if(campaignMode){workbench.inert=!pauseSheet.hidden;$('pause-button').setAttribute('aria-expanded',String(!pauseSheet.hidden));$('pause-button').setAttribute('aria-label',pauseSheet.hidden?'Open game menu':'Close game menu');}}
function paint(dt=0){renderer.render({game,run,effects,wing,trail,particles,ending:finishStarted?Math.min(1,endingElapsed/(reduced.matches?.6:1.8)):0,time},dt);}
function hud(){if(campaignMode&&!workbench.hidden){$('height').textContent=String(campaign.completed.length).padStart(2,'0');$('height-label').textContent='FLIGHTS FILED';$('best').textContent=`OF 09 · ${LEVELS.filter(l=>records.levels[l.id].collected).length} PATENTS`;$('rest-hint').hidden=true;shell.classList.remove('awaiting-flap');return;}if(campaignMode)$('height-label').textContent='METRES UP';$('height').textContent=String(Math.floor(Math.max(0,game.y-level.world.start.y))).padStart(3,'0');const r=records.levels[level.id];$('best').textContent=`BEST ${r.bestMs===null?'—':formatTime(r.bestMs)}`;$('stage').textContent=stageAt(game).title;$('patent-count').textContent=`PATENT ${run.collected.length}/1`;const waiting=['ready','playing'].includes(game.mode)&&Boolean(game.mode==='ready'||game.heldCheckpoint||game.homingCheckpoint||game.awaitFlap);shell.classList.toggle('awaiting-flap',waiting&&!paused&&workbench.hidden);$('rest-hint').hidden=!waiting||paused||!workbench.hidden;if(waiting)$('rest-hint').textContent=game.mode==='ready'?(game.heldCheckpoint==='launch'?'HOLD AIM · PULL FLAP TO FLY':'BASKET HOLD · PULL FLAP TO FLY'):game.homingCheckpoint?'BASKET CATCH · PULL FLAP TO FLY':'PULL FLAP TO RESUME';}
function clearScene(){impactRemaining=0;impactHeld=false;finishStarted=false;endingElapsed=0;wonShown=false;particles.length=trail.length=0;effects=createEffects();victory.hidden=true;pauseSheet.hidden=true;$('impact-notice').hidden=true;paused=false;last=0;time=0;}
function selectFlight(id){const selected=levelById(id);if(!selected||(campaignMode&&!unlockedLevels(campaign).includes(id)))return;cancelControls();level=selected;chapterId=level.chapterId;run=createRun(level.id);game=createGame(undefined,level.world);beginFlight(game);hasFlight=true;restoredFinish=false;selectedFlightId=null;clearScene();renderer=createRenderer(canvas,level);workbench.hidden=true;setAim(.5);setWing(0);save();hud();paint();syncSheets();aimTrack.focus({preventScroll:true});}
function renderReport(report){if(campaignMode){const next=nextFlight(campaign),nextLevel=next?levelById(next):null,chapterEnd=CHAPTERS.find(c=>c.id===level.chapterId).levelIds.at(-1)===level.id,final=campaign.completed.length===9&&level.id===LEVELS.at(-1).id;$('victory-title').textContent=final?'CAMPAIGN COMPLETE.':chapterEnd?'CHAPTER FILED.':'FLIGHT FILED.';$('report-next').hidden=!next;$('report-next').textContent=nextLevel?(nextLevel.chapterId!==level.chapterId?`NEXT CHAPTER · ${CHAPTERS.find(c=>c.id===nextLevel.chapterId).title} ↗`:`NEXT FLIGHT · ${nextLevel.title} ↗`):'';$('report-next').onclick=()=>{const id=nextFlight(campaign);if(id)selectFlight(id);};$('campaign-ending').hidden=!final;$('campaign-ending').textContent=final?`9/9 FLIGHTS FILED · ${LEVELS.filter(l=>records.levels[l.id].collected).length}/9 PATENTS FOUND. The weatherworks answers. Replay filed flights for missing scraps or a better time.`:'';}$('report-level').textContent=level.title;$('report-time').textContent=formatTime(report.elapsedMs);$('report-patents').textContent=`${report.patents}/1`;$('report-crashes').textContent=String(report.crashes);$('report-retries').textContent=String(report.retries);$('report-scope').textContent=report.eligible?'FULL FLIGHT · FROM THE LAUNCH WELL':'PRACTICE · RESUMED / BASKET RESTART';const r=records.levels[level.id];$('report-best').textContent=recordsInvalid?'Unreadable records kept unchanged.':storageFailed?'Records may not be saved: storage unavailable.':r.bestMs===null?'Start a new full flight for a local best.':`LOCAL BEST ${formatTime(r.bestMs)}`;for(const [id,key,label] of [['goal-complete','complete','FINISH'],['goal-patents','allPatents','WITH PATENT'],['goal-clean','clean','CLEAN']]){const achieved=campaignMode&&key==='complete'?campaign.completed.includes(level.id):Boolean(r[key]);$(id).textContent=`${achieved?'✓':'○'} ${label}`;$(id).classList.toggle('achieved',achieved);}}
function continueFlight(){if(!hasFlight)return;workbench.hidden=true;paused=false;last=0;renderer.resize();if(game.mode==='playing')game.awaitFlap=true;hud();paint();if(run.finished){finishStarted=true;endingElapsed=reduced.matches?.6:1.8;wonShown=true;renderReport(finishRun(run));victory.hidden=false;(campaignMode&&!$('report-next').hidden?$('report-next'):$('report-map')).focus({preventScroll:true});}else aimTrack.focus({preventScroll:true});syncSheets();}
function goalMarkup(r,id){const filed=campaignMode?campaign.completed.includes(id):r.complete;return [['complete','FINISH'],['allPatents','PATENT FINISH'],['clean','CLEAN']].map(([k,label])=>`<span class="${(k==='complete'?filed:r[k])?'achieved':''}">${(k==='complete'?filed:r[k])?'✓':'○'} ${label}</span>`).join('');}
function restartCampaign(){cancelControls();campaign=createCampaign();write(SAVE_KEY,campaign);level=levelById('rain-1');run=createRun(level.id);game=createGame(undefined,level.world);beginFlight(game);clearScene();renderer=createRenderer(canvas,level);restoredFinish=false;hasFlight=false;selectedFlightId=null;chapterId=level.chapterId;workbench.hidden=false;$('campaign-restart').open=false;renderMap();hud();paint();syncSheets();$('campaign-start').focus({preventScroll:true});}
function renderNotebook(){$('notebook-count').textContent=`${LEVELS.filter(l=>records.levels[l.id].collected).length}/9`;$('notebook-list').replaceChildren();for(const [index,l] of LEVELS.entries()){const li=document.createElement('li'),found=records.levels[l.id].collected;li.className=found?'found':'';li.dataset.patent=l.id;li.textContent=found?`✓ ${l.patent.title}`:campaignMode&&!unlockedLevels(campaign).includes(l.id)?`○ FLIGHT ${String(index+1).padStart(2,'0')} · LOCKED`:`○ ${l.title} · missing scrap`;$('notebook-list').append(li);}}
function renderMap(){if(campaignMode){const model=overview(campaign,records,selectedFlightId,hasFlight?level.id:null,run.finished);selectedFlightId=model.selectedId;renderOverview(model,{onSelect:id=>{selectedFlightId=id;renderMap();},onLaunch:(id,resumable)=>resumable?continueFlight():selectFlight(id),onReport:continueFlight,onRestart:restartCampaign,saveInvalid,formatTime});renderNotebook();warning();return;}const chapter=CHAPTERS.find(c=>c.id===chapterId);$('chapter-tabs').replaceChildren();for(const [i,c] of CHAPTERS.entries()){const b=document.createElement('button');b.textContent=`${i+1} · ${c.title.replace('The ','')}`;b.dataset.chapter=c.id;if(campaignMode)b.disabled=!c.levelIds.some(id=>unlockedLevels(campaign).includes(id));b.setAttribute('aria-current',String(c.id===chapterId));b.onclick=()=>{chapterId=c.id;renderMap();};$('chapter-tabs').append(b);}$('chapter-premise').textContent=chapter.premise;$('flight-list').replaceChildren();for(const [i,id] of chapter.levelIds.entries()){const l=levelById(id),r=records.levels[id],card=document.createElement('article');card.className='flight-card';card.innerHTML=`<h2><span class="flight-number">0${i+1}</span>${l.title}</h2><p>${l.premise}</p><div class="map-goals">${goalMarkup(r,id)}</div><button data-level="${id}"><span>FLY ↗</span><small>${r.bestMs===null?'NO LOCAL BEST':`BEST ${formatTime(r.bestMs)}`}</small></button>`;if(campaignMode&&!unlockedLevels(campaign).includes(id)){card.classList.add('locked');card.querySelector('button').disabled=true;card.querySelector('button').textContent='LOCKED · FILE THE PREVIOUS FLIGHT';}card.querySelector('button').onclick=()=>selectFlight(id);$('flight-list').append(card);}
 renderNotebook();$('continue-flight').hidden=!hasFlight;$('continue-flight').textContent=run.finished?`VIEW FILED FLIGHT · ${level.title} ↗`:`CONTINUE · ${level.title} ↗`;warning();}
function openMap(){cancelControls();save();pauseSheet.hidden=victory.hidden=true;paused=false;workbench.hidden=false;last=0;selectedFlightId=null;renderMap();hud();syncSheets();if(campaignMode){$('campaign-start').focus({preventScroll:true});return;}$('continue-flight').hidden?$('chapter-tabs').querySelector('button[aria-current=true]').focus({preventScroll:true}):$('continue-flight').focus({preventScroll:true});}
function openPause(){if(campaignMode){renderNotebook();$('campaign-restart').hidden=campaign.completed.length===0;$('campaign-new').disabled=saveInvalid;if(paused){resume();return;}menuReturn=!workbench.hidden?'map':!victory.hidden||game.mode==='won'?'report':'flight';victory.hidden=true;$('pause-title').textContent=menuReturn==='flight'?'PAUSED.':'MENU.';$('pause-resume').textContent=menuReturn==='map'?'BACK TO MAP':menuReturn==='report'?'BACK TO REPORT':'RESUME FLIGHT';$('pause-restart').hidden=$('pause-new').hidden=menuReturn!=='flight';$('pause-map').hidden=menuReturn==='map';}else if(!workbench.hidden||paused||!victory.hidden)return;cancelControls();save();paused=true;pauseSheet.hidden=false;$('pause-hint').textContent=campaignMode&&menuReturn!=='flight'?(menuReturn==='map'?'Choose an unlocked flight, or return to its saved basket.':`${level.title} is filed. Continue the route or revisit the map.`):stageAt(game).hint;syncSheets();warning();updateAudioStatus();$('pause-resume').focus({preventScroll:true});}
function resume(){pauseSheet.hidden=true;paused=false;last=0;if(campaignMode&&menuReturn==='map'){workbench.hidden=false;hud();syncSheets();$('campaign-start').focus({preventScroll:true});}else if(campaignMode&&menuReturn==='report'){wonShown=true;finishStarted=true;endingElapsed=reduced.matches?.6:1.8;victory.hidden=false;hud();syncSheets();(!$('report-next').hidden?$('report-next'):$('report-map')).focus({preventScroll:true});}else{if(game.mode==='playing')game.awaitFlap=true;hud();syncSheets();aimTrack.focus({preventScroll:true});}menuReturn=null;}
function resetBasket(){cancelControls();retryRun(run,{manual:game.mode!=='dead'});if(game.mode==='dead')revive(game);else{game=createGame(snapshot(game),level.world);beginFlight(game);}clearScene();restoredFinish=false;renderer=createRenderer(canvas,level);setAim(.5);setWing(0);save();hud();paint();syncSheets();aimTrack.focus({preventScroll:true});}
$('map-button').onclick=openMap;$('pause-button').onclick=openPause;$('pause-map').onclick=openMap;$('report-map').onclick=openMap;$('continue-flight').onclick=continueFlight;$('pause-resume').onclick=resume;$('pause-restart').onclick=resetBasket;$('impact-retry').onclick=resetBasket;
$('pause-new').onclick=$('report-replay').onclick=()=>selectFlight(level.id);
canvas.addEventListener('pointerdown',()=>{if(game.mode==='dead'){impactHeld=true;$('impact-text').textContent=`${game.cause} · IMPACT HELD`;}});
$('reset-lab').onclick=()=>{try{for(const key of [SAVE_KEY,RECORD_KEY,PREF_KEY])localStorage.removeItem(key);saveInvalid=recordsInvalid=prefsInvalid=false;storageFailed=false;records=createRecords();campaign=createCampaign();run=createRun('rain-1');level=levelById('rain-1');game=createGame(undefined,level.world);beginFlight(game);hasFlight=false;restoredFinish=false;selectedFlightId=null;workbench.hidden=false;clearScene();chapterId=level.chapterId;renderer=createRenderer(canvas,level);renderMap();syncSheets();}catch{storageFailed=true;warning();}};
for(const id of ['sound-toggle','haptic-toggle'])$(id).addEventListener('change',()=>{feedback.configure({sound:$('sound-toggle').checked,haptics:$('haptic-toggle').checked});if($('sound-toggle').checked)unlock();if(!prefsInvalid)write(PREF_KEY,{v:1,sound:$('sound-toggle').checked,haptics:$('haptic-toggle').checked});updateAudioStatus();});
document.addEventListener('keydown',e=>{const sheet=!pauseSheet.hidden?pauseSheet:!victory.hidden&&!campaignMode?victory:null;if(sheet){if(e.key==='Escape'&&sheet===pauseSheet){e.preventDefault();resume();}if(e.key==='Tab'){const items=[...sheet.querySelectorAll(campaignMode?'button:not([disabled]),input:not([disabled]),summary,a[href]':'button:not([disabled]),input')].filter(x=>{if(!x.getClientRects().length)return false;const closed=x.closest('details:not([open])');return !campaignMode||!closed||x.tagName==='SUMMARY'&&x.parentElement===closed;}),first=items[0],end=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();end?.focus();}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first?.focus();}}return;}if(campaignMode&&(!workbench.hidden||!victory.hidden)){if(e.key==='Escape'){e.preventDefault();openPause();}return;}if(!workbench.hidden)return;if(e.key==='Escape'){e.preventDefault();openPause();return;}if(game.mode==='dead'){if(e.code==='Space'||e.key==='Enter'){e.preventDefault();resetBasket();}else if(e.key.toLowerCase()==='i')impactHeld=true;return;}if(!canFly())return;if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();if(!e.repeat&&!aimKeys.has(e.key))setAim(aim+(e.key==='ArrowLeft'?-.045:.045));aimKeys.add(e.key);}if(e.code==='Space'&&!e.repeat){e.preventDefault();unlock();kick(1300);setWing(.85);}if(document.activeElement===flapTrack&&['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();if(!keyboardWing){beginStroke(stroke,wing,e.timeStamp-30);keyboardWing=true;}const next=clamp(wing+(e.key==='ArrowDown'?.25:-.25),0,1),speed=updateStroke(stroke,next,e.timeStamp,flapTrack.clientHeight-50);setWing(next);if(speed>0)kick(speed);}});
document.addEventListener('keyup',e=>{aimKeys.delete(e.key);if(['ArrowDown','ArrowUp'].includes(e.key)){keyboardWing=false;endStroke(stroke);}});
window.addEventListener('blur',()=>{cancelControls();if(game.mode==='playing')game.awaitFlap=true;});
document.addEventListener('visibilitychange',()=>{last=0;if(document.hidden){cancelControls();if(game.mode==='playing')game.awaitFlap=true;save();}});window.addEventListener('pagehide',e=>{save();});
window.addEventListener('resize',()=>{if(campaignMode&&!workbench.hidden)renderMap();renderer.resize();setAim(aim);setWing(wing);paint();});
function frame(ms){const dt=last?Math.min(.05,(ms-last)/1000):0;last=ms;if(!document.hidden&&!paused&&workbench.hidden){time+=dt;if(canFly()){const dir=(aimKeys.has('ArrowRight')?1:0)-(aimKeys.has('ArrowLeft')?1:0);if(dir)setAim(aim+dir*dt*1.4);else if(aimPointer===null&&aimKeys.size===0){const d=1-Math.exp(-18*dt);setAim(Math.abs(aim-.5)<.002?.5:aim+(.5-aim)*d);}if(flapPointer===null&&!keyboardWing&&wing>0)setWing(wing<.004?0:wing*Math.exp(-18*dt));}
 const before=game.mode,checkpoint=game.checkpoint,homing=game.homingCheckpoint;if(game.mode==='playing'){const n=Math.max(1,Math.ceil(dt/(1/120)));for(let i=0;i<n&&game.mode==='playing';i++){const from={x:game.x,y:game.y,mode:game.mode,awaitFlap:game.awaitFlap,elapsed:game.elapsed};tickRun(run,dt/n,{active:!game.awaitFlap});step(game,dt/n);if(collectPatent(run,level.patent,from,game).length){notePickup(effects,level.patent);records=noteCollection(records,level.id);saveRecords();save();cue('patent');}}if(game.checkpoint!==checkpoint)save();if((game.homingCheckpoint&&game.homingCheckpoint!==homing)||(before==='playing'&&game.mode==='ready'&&!homing)){noteCatch(effects,game.checkpoint);cue('checkpoint');}if(!reduced.matches){trail.push({x:game.x,y:game.y});if(trail.length>14)trail.shift();}}

 if(before==='playing'&&game.mode==='dead'){crashRun(run);save();cancelControls();cue('crash');impactRemaining=.48;impactHeld=false;$('impact-text').textContent=`${game.cause} · TAP SCENE TO INSPECT`;$('impact-notice').hidden=false;syncSheets();}
 if(game.mode==='dead'&&!impactHeld){impactRemaining-=dt;if(impactRemaining<=0)resetBasket();}
 if(game.mode==='won'&&!wonShown){if(!finishStarted){finishStarted=true;endingElapsed=restoredFinish?(reduced.matches?.6:1.8):0;cancelControls();const report=finishRun(run);if(!restoredFinish){records=updateRecords(records,report);if(campaignMode)campaign=fileFlight(campaign,snapshotSave(level.id,game,run));saveRecords();save();cue('quiet');}renderReport(report);syncSheets();}endingElapsed=Math.min(reduced.matches?.6:1.8,endingElapsed+dt);if(endingElapsed>=(reduced.matches?.6:1.8)){wonShown=true;cue('win');victory.hidden=false;syncSheets();(campaignMode&&!$('report-next').hidden?$('report-next'):$('report-map')).focus({preventScroll:true});}}
 for(const kind of tickEffects(effects,dt,game,level.world))cue(kind,.75);for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0)particles.splice(i,1);}hud();paint(dt);}
 requestAnimationFrame(frame);}
setAim(.5);setWing(0);renderMap();hud();paint();syncSheets();requestAnimationFrame(frame);
// Read-only diagnostics. Acceptance write fixtures are added only to responses.
window.stormLab={state:()=>structuredClone(game),run:()=>structuredClone(run),records:()=>structuredClone(records),view:()=>renderer.view(),storage:()=>({saveInvalid,recordsInvalid,prefsInvalid,storageFailed}),progress:()=>campaignMode?structuredClone(campaign):null,catalog:()=>LEVELS.map(l=>({id:l.id,chapterId:l.chapterId,title:l.title})),feedback:()=>feedback.state()};
